apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  namespace: argo-cd
spec:
  project: kubernetes-apps
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflared
  source:
    repoURL: {{ .Values.repoURL }}
    path: kubernetes-apps/apps/cloudflared
    targetRevision: {{ .Values.targetRevision }}
    {{- if .Values.cloudflared -}}
      helm:
        values: |-
          cloudflared:
          {{- toYaml .Values.cloudflared | nindent 10 }}
    {{- end -}}
