apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-apps
  namespace: argo-cd
spec:
  destination:
    namespace: argo-cd
    server: https://kubernetes.default.svc
  project: argo-cd-internal
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  source:
    path: kubernetes-apps/chart
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    helm:
      values: |
        repoURL: {{ .Values.repoURL }}
        targetRevision: {{ .Values.targetRevision }}

        {{- if (.Values.apps) -}}
        {{- toYaml .Values.apps }}
        {{- end -}}
