apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argo-cd-internal
  namespace: argo-cd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: 'argo-cd'
      server: 'https://kubernetes.default.svc'
  sourceRepos:
    - '*'
