traefik:
  image:
    name: kubitodev/traefik-cloudflared-source-ip
    tag: 1.0.4
  ingressClass:
    enabled: true
    isDefaultClass: true
  providers:
    kubernetesCRD:
      allowCrossNamespace: true
    kubernetesIngress:
      allowCrossNamespace: true
  service:
    type: ClusterIP

cloudflared:
  ingress:
    - service: https://traefik.traefik.svc.cluster.local:443
      originRequest:
        originServerName: cluster.tristanxr.com
