cloudflared:
  image:
    tag: latest
  warpRouting: true
  replicaCount: 1
  ingress:
    - hostname: cluster.tristanxr.com
      service: http://argo-cd-argocd-server.argo-cd.svc.cluster.local:80
    - service: http_status:404
