apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: traefik
spec:
  selector:
    matchLabels:
      app: cloudflared
  replicas: 1
  template:
    metadata:
      labels:
        app: cloudflared
      annotations:
        checksum/tunnel-id: {{ sha256sum .Values.cloudflared.tunnelID }}
        checksum/ingress: {{ .Values.cloudflared.ingress | toJson | sha256sum }}
        checksum/auth: {{ .Values.cloudflared.auth | toJson | sha256sum }}
        checksum/warp-routing: {{ .Values.cloudflared.warpRouting | toJson | sha256sum }}
    spec:
      containers:
      - args:
        - tunnel
        - --no-autoupdate
        - --config
        - /etc/cloudflared/config.yaml
        - run
        name: cloudflared
        image: "cloudflare/cloudflared:2022.7.1"
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /etc/cloudflared/tunnel-config.json
          name: tunnel-secret-volume
          subPath: tunnel-config.json
        - mountPath: /etc/cloudflared/config.yaml
          name: cloudflared-config-volume
          subPath: config.yaml
      imagePullSecrets:
      - name: tunnel-secret
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: tunnel-secret-volume
        secret:
          defaultMode: 420
          optional: false
          secretName: tunnel-secret
      - name: cloudflared-config-volume
        configMap:
          defaultMode: 420
          name: cloudflared
          optional: false
