apiVersion: v1
kind: Secret
metadata:
  name: argo-workflows-sso
  namespace: argo-workflows
stringData:
  client-id: "argo-workflows-sso"
  client-secret: {{ .Values.argoWorkflows.ssoClientSecret | quote }}
