argo-workflows:
  controller:
    telemetryConfig:
      enabled: true
    metricsConfig:
      enabled: true
  server:
    secure: true
    baseHref: /argo-workflows
    extraArgs:
      - --auth-mode=sso
    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/rewrite-target: "/argo-workflows/$2"
      hosts: ["cluster.tristanxr.com"]
      paths: ["/argo-workflows(/|$)(.*)"]
    sso:
      issuer: "https://cluster.tristanxr.com/keycloak/realms/master"
      redirectUrl: "https://cluster.tristanxr.com/keycloak"
      insecureSkipVerify: true
      scopes:
        - groups
        - email
        - profile
        - openid
      clientId:
        name: argo-workflows-sso
        key: client-id
      clientSecret:
        name: argo-workflows-sso
        key: client-secret
      rbac:
        enabled: true
